version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/rust-*"
    schedule:
      interval: "monthly"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directories:
      - "/ts-events-api"
      - "/js-growzone"
    schedule:
      interval: "monthly"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
